[tool.poetry]
name = "fd-converter"
version = "0.1.1"
description = ""
authors = ["dimnissv <dimnissv@yandex.kz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
